services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify
      POSTGRES_DB: spotify_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
